# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

ci:
    autofix_commit_msg: |
      [pre-commit.ci] auto code formatting
    autofix_prs: false
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: quarterly
    submodules: false

# Please update the rev: SHAs below with this command:
# pre-commit autoupdate --freeze
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 5ba58aca0bd5bc7c0e1c0fc45af2e88d6a2bde83  # frozen: v0.14.10
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-spdx
        name: Check SPDX Headers
        entry: python ./toolshed/check_spdx.py
        language: python
        additional_dependencies:
          - https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl
        exclude: '(.*pixi\.lock)|(\.git_archival\.txt)|uv\.lock'
        args: ["--fix"]

      - id: no-markdown-in-docs-source
        name: Prevent markdown files in docs/source directories
        entry: bash -c
        args:
          - 'for file in "$@"; do >&2 echo "error: markdown file "$file" found in a docs/source directory. Only reST (.rst) is allowed"; done && exit 1'
          - "_" # fake script name, because bash considers $0 (the first argument) to be the script name
        language: system
        files: '^.*/docs/source/.*\.md$'

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
    - id: check-added-large-files
      exclude: 'cuda_bindings/cuda/bindings/nvml\.pyx|uv\.lock'
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316"  # frozen: v1.10.0
    hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "3fa3bf0572b3af5e0b2fba0b6e76a1e0c4e1fdee"  # frozen: v1.16.1
    hooks:
    - id: mypy
      name: mypy-pathfinder
      args: ["--config-file=cuda_pathfinder/pyproject.toml"]
      files: "^cuda_pathfinder/"
      exclude: "^cuda_pathfinder/tests/"

  - repo: https://github.com/rhysd/actionlint
    rev: "a1bcb27e3e8727e0b92d7d36c5a6f4b076b32b34"  # frozen: v1.7.7
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: "48ca7bf3eb3d0bba6c3e76ba43b0a9e0a1f9bcc9"  # frozen: v0.16.6
    hooks:
    - id: cython-lint
      args: ['--max-line-length=320']
