# Copyright (c) 2024-2025, NVIDIA CORPORATION.
#
# SPDX-License-Identifier: Apache-2.0

ci:
    autofix_commit_msg: |
      [pre-commit.ci] auto code formatting
    autofix_prs: false
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: quarterly
    skip: [bandit]
    submodules: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 971923581912ef60a6b70dbf0c3e9a39563c9d47  #v0.11.4
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-spdx
        name: Check SPDX-License-Identifier
        entry: python ./toolshed/check_spdx.py
        language: python
        additional_dependencies:
          - pathspec==0.12.1

  - repo: https://github.com/PyCQA/bandit
    rev: 8ff25e07e487f143571cc305e56dd0253c60bc7b  #v1.8.3
    hooks:
      - id: bandit
        args:
          - --ini
          - .bandit

default_language_version:
      python: python3
