# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NVIDIA-SOFTWARE-LICENSE

name: cuda-python-docs
channels:
  - conda-forge
dependencies:
  # ATTENTION: This dependency list is duplicated in
  #            toolshed/setup-docs-env.sh. Please KEEP THEM IN SYNC!
  - cython
  - myst-parser
  - numpy
  - numpydoc
  - pip
  - pydata-sphinx-theme
  - pytest
  - scipy
  - sphinx <8.2.0
  - sphinx-copybutton
  - myst-nb
  - enum_tools
  - sphinx-toolbox
  - pyclibrary
  - pip:
    - nvidia-sphinx-theme
