# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: "CI: Release"

description: Manually-triggered release workflow. Must have a release note in the draft state and the release commit tagged.

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Component to release"
        required: true
        type: choice
        options:
          - cuda-core
          - cuda-bindings
          - cuda-pathfinder
          - cuda-python
          - all
      git-tag:
        description: "The release git tag"
        required: true
        type: string
      run-id:
        description: "The GHA run ID that generated validated artifacts"
        required: true
        type: string
      build-ctk-ver:
        type: string
        required: true
      wheel-dst:
        description: "Which wheel index to publish to?"
        required: true
        type: choice
        options:
          - testpypi
          - pypi

defaults:
  run:
    shell: bash --noprofile --norc -xeuo pipefail {0}

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if draft exists for the tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tags=
          for i in $(gh release list -R ${{ github.repository }} --json tagName --jq '.[]| .tagName'); do
            tags+=( $i )
          done
          is_draft=
          for i in $(gh release list -R ${{ github.repository }} --json isDraft --jq '.[]| .isDraft'); do
            is_draft+=( $i )
          done

          found=0
          for idx in ${!tags[@]}; do
            if [[ "${tags[$idx]}" == "${{ inputs.git-tag }}" ]]; then
              echo "found ${{ inputs.git-tag }}"
              found=1
              if [[ "${is_draft[$idx]}" != "true" ]]; then
                echo "the release note is not in draft state"
                exit 1
              fi
              break
            fi
          done
          if [[ "$found" == 0 ]]; then
            echo "the release is not yet tagged"
            exit 1
          fi

  doc:
    name: Build release docs
    if: ${{ github.repository_owner == 'nvidia' }}
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    needs:
      - check-tag
    secrets: inherit
    uses: ./.github/workflows/build-docs.yml
    with:
      build-ctk-ver: ${{ inputs.build-ctk-ver }}
      component: ${{ inputs.component }}
      git-tag: ${{ inputs.git-tag }}
      run-id: ${{ inputs.run-id }}
      is-release: true

  upload-archive:
    name: Upload source archive
    permissions:
      contents: write
    needs:
      - check-tag
    secrets: inherit
    uses: ./.github/workflows/release-upload.yml
    with:
      git-tag: ${{ inputs.git-tag }}
      run-id: ${{ inputs.run-id }}
      component: ${{ inputs.component }}

  publish-wheels:
    name: Publish wheels
    runs-on: ubuntu-latest
    needs:
      - check-tag
    environment:
      name: ${{ inputs.wheel-dst }}
      url: https://${{ (inputs.wheel-dst == 'testpypi' && 'test.') || '' }}pypi.org/p/${{ inputs.component }}/
    permissions:
      id-token: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Download component wheels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./ci/tools/download-wheels "${{ inputs.run-id }}" "${{ inputs.component }}" "${{ github.repository }}" "dist"

      - name: Publish package distributions to PyPI
        if: ${{ inputs.wheel-dst == 'pypi' }}
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4

      - name: Publish package distributions to TestPyPI
        if: ${{ inputs.wheel-dst == 'testpypi' }}
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/

  # TODO: add another job to make the release leave the draft state?
